site.github.theme: jekyll-theme-cayman
site.github.mydata: curl https://api.github.com/users/atutorlangs/starred
site.github.github: [metadata]
site.github.gems:
    - jekyll-sitemap
    - jekyll-github-metadata
    - jekyll-git_metadata
