site.github.theme: jekyll-theme-cayman
site.github.github: [metadata]
site.github.gems:
    - jekyll-sitemap
    - jekyll-github-metadata
    - jekyll-git_metadata

site.github.highlighter: rouge
site.github.defaults:
    -   
        scope:
            path: ""
            type: "pages"
        values:
            layout: "home"
    -        
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
